spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_info_sys?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 'Yun.123456'
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: root
    password: 123456